### ISSUE TITLE
TemplatedMessage type does not allow Metadata

### ISSUE THREAD

**Issue by jfedyczak** [wildbit/postmark.js#50]
There is no Metadata field in TemplatedMessage type.

**Comment by ibalosh** [comment]
Hi @jfedyczak 

thank you for reporting the issue, I will see to check it out this week.

**Comment by ibalosh** [comment]
Hi @jfedyczak 

we just pushed an update which should resolve this issue.

Igor

**Comment by tsongas** [comment]
@ibalosh I think you forgot to add the Metadata field to the constructor?

```
export declare class TemplatedMessage {
    TemplateId?: number;
    TemplateAlias?: string;
    TemplateModel: object;
    InlineCss?: boolean;
    From: string;
    To?: string;
    Cc?: string;
    Bcc?: string;
    ReplyTo?: string;
    MessageStream?: string;
    Tag?: string;
    TrackOpens?: boolean;
    TrackLinks?: LinkTrackingOptions;
    Headers?: Header[];
    Metadata?: Hash<string>;
    Attachments?: Attachment[];
    constructor(from: string, templateIdOrAlias: (number | string), templateModel: object, to?: string, cc?: string, bcc?: string, replyTo?: string, tag?: string, trackOpens?: boolean, trackLinks?: LinkTrackingOptions, headers?: Header[], attachments?: Attachment[]);
}
```

**Comment by ibalosh** [comment]
Hi @tsongas 

constructor is intended to be used when initialising object with most important parameters. It's not intended to support all parameters. Even the current constructor is very generous. 

To initialise metadata, we suggest to either create object and then set the additional parameters you plan to use, or just use all the parameters you need for sending like:

```
client.sendEmailWithTemplate({
  TemplateAlias: 'welcome', From: 'from@example.com', To: 'to@example.com', TemplateModel: {}, Metadata: {'a': 'b'}
})
```
